### ISSUE TITLE
Adding Builder Integration to Qwik Breaks Build

### ISSUE THREAD

**Issue by kaBeech** [BuilderIO/builder#1322]
**Describe the bug**
Adding the Builder.io integration to a Qwik project breaks the build and won't properly integrate with the Builder Visual Editor

**To Reproduce**
1. Create a new Qwik app using npm create qwik@latest and the Basic starter 
2. Install the Qwik SDK
3. Replace the contents of src/routes/index.tsx with the boilerplate code [here](https://www.builder.io/c/docs/integrating-builder-pages) and add a valid Public API key
4. npm run preview

**Expected behavior**
Qwik site is built and preview server is launched

**Screenshots**
![Qwik-Builder-Screenshot-2](https://user-images.githubusercontent.com/97925125/197616326-c86739df-3127-42a7-9715-ae80719e5d91.png)

**Additional context**
Looks like this is due to old references in the codebase:

```
$ npm run preview

> preview
> qwik build preview && vite preview --open


vite build
vite build --ssr src/entry.preview.tsx

vite v3.1.7 building for production...
✓ 98 modules transformed.
'_useMutableProps' is not exported by node_modules/@builder.io/qwik/core.min.mjs, imported by src/s_ca0svhikr5g.js
file: /.../builder-io-3/qwik-app/src/s_ca0svhikr5g.js:2:9
1: import { _track } from "../node_modules/@builder.io/sdk-qwik/lib/index.qwik";
2: import { _useMutableProps } from "@builder.io/qwik";
            ^
3: import { allRegisteredComponents } from "../node_modules/@builder.io/sdk-qwik/lib/index.qwik";
4: import { canTrackToUse } from "../node_modules/@builder.io/sdk-qwik/lib/index.qwik";
error during build:
Error: '_useMutableProps' is not exported by node_modules/@builder.io/qwik/core.min.mjs, imported by src/s_ca0svhikr5g.js
    at error (file:///.../qwik-app/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///.../qwik-app/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///.../qwik-app/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///.../qwik-app/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at ReturnValueScope.findVariable (file:///.../builder-io-3/qwik-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///.../qwik-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at TrackingScope.findVariable (file:///.../qwik-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at BlockScope.findVariable (file:///..,/qwik-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at TrackingScope.findVariable (file:///.../qwik-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at BlockScope.findVariable (file:///.../qwik-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)

```
I have a possible fix that I have tested - will add PR shortly. Thank you!

Edit - I may end up closing this issue myself without merging. I have a workaround that works by locally removing instances of _useMutableProps from node_modules/@builder.io/sdk-qwik/lib/index.qwik.cjs and node_modules/@builder.io/sdk-qwik/lib/index.qwik.mjs, but I'm not actually sure whether this is even the correct repo to make the change in. I discovered the Builder discord server and am checking in there before progressing further

**Comment by kaBeech** [comment]
Issue is resolved. Thank you!
