### ISSUE TITLE
Unable to add state binding to a section

### ISSUE THREAD

**Issue by NotoriousGOR** [BuilderIO/builder#2367]
**Describe the bug**
I am building a notification banner with a button to update the `state.hidden` to hide the banner. The issue is when I add the data binding to the banner itself (box in builder), I get an error saying, "ReferenceError: process is not defined."

**To Reproduce**
1. Add Section in Builder
2. Add Box with content and button to hide
3. Follow Builder's tutorial video: https://www.youtube.com/watch?v=TmbBHwcJ6vg&t=12s
4. Go to your local dev instance and check the console

**Expected behavior**
I should be able to toggle custom builder state

**Screenshots**

**Additional context**

Full error log:

```
ReferenceError: process is not defined
    at React (/node_modules/@builder.io/react/src/functions/apply-patch-with-mutation.ts:43:13)
    at BuilderBlock.renderInto (/node_modules/@builder.io/react/src/components/builder-block.component.tsx:556:8)
    at BuilderBlock.content [as contents] (/node_modules/@builder.io/react/src/components/builder-blocks.component.tsx:153:10)
    
Package version: "@builder.io/react": "^3.0.4"
```

**Comment by samijaber** [comment]
Fixed in https://github.com/BuilderIO/builder/pull/2376#pullrequestreview-1522979710
