### ISSUE TITLE
[nuxt] Unknown file extension ".css"

### ISSUE THREAD

**Issue by 20x-dz** [BuilderIO/builder#2917]
**Describe the bug**
After installing any version after v0.0.8 I get the following error: `Unknown file extension ".css" for /var/task/node_modules/@builder.io/sdk-vue/vue3/lib/node/style.css`

**To Reproduce**
1. install latest nuxt3
2. install latest @builder.io/sdk-vue
3. Adjust the [example](https://github.com/BuilderIO/builder/blob/main/examples/vue/nuxt-3/app.vue) to work with >0.0.8 releases (remove style import)
4. `npm run dev`
5. Visit http://localhost:3000 (nuxt defaults, ymmv)

**Expected behavior**
The SDK should not throw import errors.

**Screenshots**
![image](https://github.com/BuilderIO/builder/assets/113644268/40eecede-fe82-4b6b-b09d-92f751bf30ad)

**Additional context**
Already tried [transpiling](https://nuxt.com/docs/api/nuxt-config#transpile), but then `npm run build` fails with the following error:

```
[13:10:31.370] [log] Nuxt 3.9.1 with Nitro 2.8.1
[13:10:32.672] [info] [nuxt:tailwindcss] Using Tailwind CSS from ~/assets/css/tailwind.css
[13:10:34.790] [info] Building client...
[13:10:34.802] [info] [36mvite v5.0.11 [32mbuilding for production...[36m[39m
[13:10:34.830] [info] transforming...
[13:10:36.043] [info] [32m✓[39m 93 modules transformed.
[13:10:40.196] [32mInspect report generated at[39m [2m/vercel/path0/frontend/.nuxt/analyze/.vite-inspect[22m
[13:10:40.197] [error] [31m[commonjs--resolver] Missing "./vue3/css" specifier in "@builder.io/sdk-vue" package[39m
[13:10:40.197] [error] Nuxt Build Error: Missing "./vue3/css" specifier in "@builder.io/sdk-vue" package
[13:10:40.197]   at e (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:21914:25)
[13:10:40.197]   at n (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:21914:627)
[13:10:40.197]   at o (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:21914:1297)
[13:10:40.197]   at resolveExportsOrImports (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29466:20)
[13:10:40.197]   at resolveDeepImport (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29485:31)
[13:10:40.198]   at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29210:20)
[13:10:40.198]   at Object.resolveId (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:28978:28)
[13:10:40.198]   at node_modules/vite-plugin-inspect/dist/index.mjs:434:26
[13:10:40.198]   at plugin.<computed> (node_modules/vite-plugin-inspect/dist/index.mjs:363:14)
[13:10:40.198]   at node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:18670:40
[13:10:40.246] Error: Command "npm run build" exited with 1
[13:10:40.611] 
```

Similar issues from around the web:
* https://github.com/nuxt/nuxt/issues/19129

**Comment by Kapil685838** [comment]
Hi builder team,

I also have the same issue while integrating builder.io with Nuxt-3(version-3.9.3) and builder.io/skd-vue(version-0.10.0).

This is the error reference that I have
![image](https://github.com/BuilderIO/builder/assets/108571992/5b993e2d-9164-4134-88bf-2e41d054d806)

These versions reference that I am using
![image](https://github.com/BuilderIO/builder/assets/108571992/df73901b-591d-494c-ae29-92ba12376276)

This is the nuxt configuration that I did for the builder.io setup
![image](https://github.com/BuilderIO/builder/assets/108571992/bda68fa5-04a4-4055-a1f2-2c3491edd15d)

Please take a look into this issue and provide me with a solution for this.

Thanks!

**Comment by samijaber** [comment]
Thanks for reporting folks. You need to transpile the SDK in `nuxt.config.js`'s:

```js
export default defineNuxtConfig({
  build: {
    /**
     * You need to transpile the Builder.io Vue SDK for it to work correctly.
     */
    transpile: ['@builder.io/sdk-vue'],
  },
});
```

PR incoming with updates to the examples and README's https://github.com/BuilderIO/builder/pull/2918

**Comment by SurinderSing** [comment]
@samijaber thank you it is working now

**Comment by SurinderSing** [comment]
@samijaber but i have another issue i css when ever i create a button with builder.io the styling on it doesn't work because
(reset : 'all') property is taking higher specificity.

![Uploading image.png…]()

**Comment by 20x-dz** [comment]
@SurinderSing  Please use a dedicated issue for your problem.

@samijaber Thank you very much for your swift response and your work on #2918. As mentioned in the initial report, transpiling results in an error when running building. But I'll gladly wait for #2918 to be finalized/merged and retest afterwards.

**Comment by samijaber** [comment]
@20x-dz your initial report indicates that you were still using the `/css` import, that's been removed. See the updated example and changelogs

https://github.com/BuilderIO/builder/blob/main/packages/sdks/output/vue/CHANGELOG.md#minor-changes-2
https://github.com/BuilderIO/builder/tree/main/examples/vue/nuxt-3

**Comment by 20x-dz** [comment]
> @20x-dz your initial report indicates that you were still using the `/css` import, that's been removed. See the updated example and changelogs
> 
> https://github.com/BuilderIO/builder/blob/main/packages/sdks/output/vue/CHANGELOG.md#minor-changes-2 https://github.com/BuilderIO/builder/tree/main/examples/vue/nuxt-3

On the contrary:

> * Adjust the [example](https://github.com/BuilderIO/builder/blob/main/examples/vue/nuxt-3/app.vue) to work with >0.0.8 releases (remove style import)

The style imports in the template were removed as indicated in the readme following the changes introduced in v0.0.8.

But I'll check the upcoming release that is in the pipeline right now and will report back.

Thank you for your support!

**Comment by Kapil685838** [comment]
> Thanks for reporting folks. You need to transpile the SDK in `nuxt.config.js`'s:
> 
> ```js
> export default defineNuxtConfig({
>   build: {
>     /**
>      * You need to transpile the Builder.io Vue SDK for it to work correctly.
>      */
>     transpile: ['@builder.io/sdk-vue'],
>   },
> });
> ```
> 
> PR incoming with updates to the examples and README's #2918

Thanks @samijaber now things are working fine.

**Comment by 20x-dz** [comment]
Thank you very much @samijaber , works now in the development environment. Building fails though when using a catchall page (#2925)… 😅

**Comment by samijaber** [comment]
I have added a Nuxt module that you can use to import the CSS correctly. You should also no longer `transpile` the package, as that caused other issues described by @20x-dz .

See https://github.com/BuilderIO/builder/tree/main/packages/sdks/output/vue#getting-started for instructions
