### ISSUE TITLE
Error: Cannot find module 'isolated-vm'

### ISSUE THREAD

**Issue by 20x-dz** [BuilderIO/builder#2933]
**Describe the bug**
Following up on #2917 and #2925: Now that both running the development server and building the application work, I get the following error when visiting [the deployment on vercel](https://builder-vue-test.vercel.app/) from my [nuxt example](https://github.com/20x-dz/builder-vue-test):

```
Error: Cannot find module 'isolated-vm'
Require stack:
- /var/task/node_modules/@builder.io/sdk-vue/lib/node/index.e41a8ad1.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at r.<computed>.e._load (/opt/node-bridge/bridge-server-NOEMJORR.js:1:1574)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at file:///var/task/node_modules/@builder.io/sdk-vue/lib/node/index.e41a8ad1.js:201:13
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/@builder.io/sdk-vue/lib/node/index.e41a8ad1.js'
  ]
}
```

**To Reproduce**
1. Create [hobby account on vercel](https://vercel.com/docs/accounts/plans/hobby)
2. Fork [nuxt example](https://github.com/20x-dz/builder-vue-test) on GitHub
3. Add fork as project to vercel and 
4. visit the production URL after the initial deployment

**Expected behavior**
To render the builder.io examples.

**Additional context**
I already researched a little bit and I couldn't find anything related.

And I also don't see what changed between the last working version [(v0.7.6) and (v0.11.2)](https://github.com/BuilderIO/builder/compare/%40builder.io/sdk-vue%400.7.6...%40builder.io/sdk-vue%400.11.2) to trigger this error in the first place. f5ea331 popped up, but that is react related. And the dependency was already in vue before that change…

Previous issue reports (probably unrelated):
 * #2917 
 * #2925

**Comment by behzadsp** [comment]
I had the same issue but its fixed with running the npm update command, but now im getting another error in browser console and the builder.io component is not rendering:
`Uncaught (in promise) TypeError: The specifier “@builder.io/sdk-vue” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.`

**Comment by 20x-dz** [comment]
> I had the same issue but its fixed with running the npm update command
Care to share some details? Node version? Maybe create a PR on my Nuxt example for reproducibility? Thx!

**Comment by samijaber** [comment]
The issue is that your deployment is using the Node bundle instead of the Edge bundle:

- node bundle: `@builder.io/sdk-vue/lib/node`
- edge bundle: `@builder.io/sdk-vue/lib/edge`

I am not sure why that is happening, since `edge-light` ([Vercel's environment name](https://runtime-keys.proposal.wintercg.org/#edge-light)) is configured to use the correct bundle in the `package.json`: https://github.com/BuilderIO/builder/blob/8a88374ed923325c0414a23b3da17c531370dd62/packages/sdks/output/vue/package.json#L28-L73

My best guess is that there is an issue either in Nuxt or Vercel's build configuration such that it is grabbing the wrong bundle. Not sure how to go about fixing that unfortunately.

What I can do is add an `/edge` export subpath so that you can explicitly import the edge bundle in your webapp.

**Comment by samijaber** [comment]
if you try https://github.com/BuilderIO/builder/releases/tag/%40builder.io%2Fsdk-vue%400.11.3, you should be able to import `@builder.io/sdk-vue/edge` which will not import `isolated-vm`. This should fix your issue.

**Comment by 20x-dz** [comment]
> if you try https://github.com/BuilderIO/builder/releases/tag/%40builder.io%2Fsdk-vue%400.11.3, you should be able to import `@builder.io/sdk-vue/edge` which will not import `isolated-vm`. This should fix your issue.

OMG, it does! Thanks a lot! 🥳 💯 👍 🥇 

Any idea where I should open an issue to have the subpath export fixed? Vercel? Nuxt/Nitro? Both? …

**Comment by samijaber** [comment]
@20x-dz I am honestly not sure! One of those tools is the culprit, but I don't know which 😅
