### ISSUE TITLE
`npm run dev` error caused by `@builder.io/dev-tools`: package.json invalid path

### ISSUE THREAD

**Issue by ijustwannacodetoday** [BuilderIO/builder#3035]
Hi, I just signed up for Builder, I’m on the “Welcome to Builder” screen, using “Integrate your existing project”.
I get an error when starting dev server - `Error: Invalid path: C:\dev\project\code\package.json (7341)` - when executing `npm run dev` on Windows.

**Describe the bug**
I created a new Qwik site using Cloudflare Pages integration following [Deploy a Qwik site · Cloudflare Pages docs](https://developers.cloudflare.com/pages/framework-guides/deploy-a-qwik-site/).
Then, I signed up at [builder.io](http://builder.io/), and got to the “Welcome to Builder” screen, which said to run `npm init builder.io@latest --existing` to “Integrate your existing project”.
After that, I ran `npm install` and `npm run dev`, but it errors out right away with the following:
```
> dev
> vite --mode ssr

error when starting dev server:
Error: Invalid path: C:\dev\project\code\package.json (7341)
    at m (file:///C:/dev/project/code/node_modules/@builder.io/dev-tools/node/index.mjs:1:2907)
    at Object.readFile (file:///C:/dev/project/code/node_modules/@builder.io/dev-tools/node/index.mjs:1:1629)
    at f (file:///C:/dev/project/code/node_modules/@builder.io/dev-tools/node/index.mjs:1:466)
    at u (file:///C:/dev/project/code/node_modules/@builder.io/dev-tools/node/index.mjs:1:583)
    at $ (file:///C:/dev/project/code/node_modules/@builder.io/dev-tools/node/index.mjs:1:2704)
    at configureServer (file:///C:/dev/project/code/node_modules/@builder.io/dev-tools/vite/index.mjs:3:293)
    at _createServer (file:///C:/dev/project/code/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:64550:30)
    at async CAC.<anonymous> (file:///C:/dev/project/code/node_modules/vite/dist/node/cli.js:762:24)
```

**To Reproduce**
Steps to reproduce the behavior **on Windows**:
1. `npm create cloudflare@latest my-qwik-app -- --framework=qwik`
2. `npm init builder.io@latest --existing`
3. `npm install`
4. `npm run dev`

**Expected behavior**
Qwik dev server working locally on a Windows machine after integrating Builder.

**Additional context**
These are the dependencies added:
```
    "@builder.io/dev-tools": "^0.2.19",
    "@builder.io/sdk-qwik": "^0.14.3"
```
And it fails here:
```
if(!o.startsWith(n))throw new Error(`Invalid path: ${o} (7341)`)
```
Debugging values:
```
n: 'C:/dev/project/code'
o: 'C:\dev\project\code\package.json'
```
The issue seems to stem from a non-normalized path separator.

Could anyone please help fix this?

**Comment by Megasware128** [comment]
I have the same issue with the vite qwik template. I'm also running Windows

**Comment by freebreix** [comment]
Encountered the same error. Not a good experience using these great tech together so far.
```
npm create qwik@latest
npm run qwik add builder.io
npm run dev
```
