### ISSUE TITLE
showIf for qwik sdk

### ISSUE THREAD

**Issue by VishaKsu** [BuilderIO/builder#3577]
Does qwik sdk support `showIf`? 

Currently attempt to add it throws error
```
[vite] Internal server error: Value cannot be serialized in _[15].inputs[2].showIf, because it's a function named "showIf". You might need to convert it to a QRL using $(fn):

const showIf = $((options)=>{
                return options.isLink === false;
            });

Please check out https://qwik.dev/docs/advanced/qrl/ for more information.
```
conversion to QRL doesn't help, it throws errors inside builder editor:
```
Evaluation error: SyntaxError: Unexpected token 'function'
    at new Function (<anonymous>)
    at safeEvaluate (main.7d24c41c.chunk.js:1294:136)
    at 236.0b11667e.chunk.js:201:34575
    at Array.filter (<anonymous>)
    at FieldsForm_FieldsFormEditor.render (236.0b11667e.chunk.js:201:34293)
    at allowStateChanges (216.777cc639.chunk.js:30:14474)
    at 216.777cc639.chunk.js:422:1276
    at trackDerivedFunction (216.777cc639.chunk.js:30:10780)
    at Reaction2.track (216.777cc639.chunk.js:45:1548)
    at FieldsForm_FieldsFormEditor.reactiveRender [as render] (216.777cc639.chunk.js:422:1185) in return (function async function(...args) {
    const fn = invokeFn.call(this, tryGetInvokeContext());
    const result = await fn(...args);
    return result;
  }).apply(this, arguments)
```

**Comment by samijaber** [comment]
Can you please provide a full example outlining how you're trying to use `showIf`? what value are you passing?

**Comment by VishaKsu** [comment]
I've tried to pass function:

```
export const SliderWithProductsBuilder: RegisteredComponent = {
  component: SliderWithProducts,
  name: 'Slider With Products',
  canHaveChildren: true,
  inputs: [
    {
      showIf: (options)=>{
        return !!options.get("isLink");
      },
      name: 'showArrows',
      type: 'boolean',
      defaultValue: true,
    },
    {
      name: 'isLink',
      type: 'boolean',
      defaultValue: true,
    },
   ]
}
```

but notices that I can also pass string, so I tried stringified version and it worked, sorry for disturbing

```
export const SliderWithProductsBuilder: RegisteredComponent = {
  component: SliderWithProducts,
  name: 'Slider With Products',
  canHaveChildren: true,
  inputs: [
    {
      showIf: '!!options.get("isLink")',
      name: 'showArrows',
      type: 'boolean',
      defaultValue: true,
    },
    {
      name: 'isLink',
      type: 'boolean',
      defaultValue: true,
    },
   ]
}
```

**Comment by samijaber** [comment]
Glad the stringified version works for you. We have logged a ticket internally that the regular function does not stringify properly, and will look into fixing that as well.

Thanks for reporting!
