### ISSUE TITLE
Hard crash when `JSON.parse` receives non-JSON content

### ISSUE THREAD

**Issue by tonytamps** [BuilderIO/builder#476]
I was testing query parameters with the Builder SDK when apparently I tested too many iterations and Google blocked me from further queries...

I get this error in my terminal
```
undefined:1
<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/tony/code/project/node_modules/@builder.io/sdk/dist/index.cjs.js:2060:34)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error Command failed with exit code 1.
```

Which renders into this 
![image](https://user-images.githubusercontent.com/2356776/119421145-27f0ea00-bd52-11eb-9d82-cb04ed88fdd4.png)

While this is a bit of a pain, I can understand this. They think I'm a bot and they're protecting your infrastructure. I suspect I'll be allowed to query again soon.

The issue I have is that this error causes our app to hard crash and even though the `builder.get` is wrapped in a try/catch the line `@builder.io/sdk/dist/index.cjs.js:2060:34` still manages to hard crash the process. Our error handling doesn't get a chance to catch the error.

I believe this might be related the an outage we experienced a few days ago too where non-JSON content from an `Internal Error` was being thrown.

**Comment by mrkoreye** [comment]
Addressed in https://github.com/BuilderIO/builder/pull/477

**Comment by steve8708** [comment]
published to NPM in `@builder.io/sdk@1.1.23-11` and `@builder.io/react@1.1.45-23`

**Comment by tonytamps** [comment]
Fantastic, thank you 🙇
