### ISSUE TITLE
Build fainling for Angular after update from 1.0.78 to latest version

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#57]
After updating `@builder.io/angular` package to latest version angular build is failing:

<img width="1220" alt="Screenshot 2020-02-03 at 16 41 07" src="https://user-images.githubusercontent.com/22659410/73667152-22c2e400-46a4-11ea-85f5-c6d60b69400a.png">

```
ERROR in /Users/lyczos/workspace/knowde-frontend/node_modules/@builder.io/angular/dist/fesm5/builder.io-angular.js
Module build failed (from /Users/lyczos/workspace/knowde-frontend/node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/lyczos/workspace/knowde-frontend/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/Users/lyczos/workspace/knowde-frontend/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/Users/lyczos/workspace/knowde-frontend/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/Users/lyczos/workspace/knowde-frontend/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/Users/lyczos/workspace/knowde-frontend/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/lyczos/workspace/knowde-frontend/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/lyczos/workspace/knowde-frontend/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/Users/lyczos/workspace/knowde-frontend/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/lyczos/workspace/knowde-frontend/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/lyczos/workspace/knowde-frontend/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/Users/lyczos/workspace/knowde-frontend/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/lyczos/workspace/knowde-frontend/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/lyczos/workspace/knowde-frontend/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/Users/lyczos/workspace/knowde-frontend/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/lyczos/workspace/knowde-frontend/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/lyczos/workspace/knowde-frontend/node_modules/typescript/lib/typescript.js:16599:21)

```

**Comment by ca136** [comment]
@lyczos I think you may need to update your version of `@angular-devkit`
https://github.com/angular/angular-cli/issues/15703.

Looks like the Angular 8 lib packager has some potential breaking changes for older versions of Angular. 

I tried updating in the example app, and build is working ok: https://github.com/BuilderIO/builder/pull/58

**Comment by lyczos** [comment]
@ca136 Thanks! It's working right now!
