### ISSUE TITLE
IE11 CustomEvent error - polyfill needed

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#61]
I getting this kind of error when trying to run builder.io content on IE11.

I spent some time on investigation and I think the reason of this error is CustomEvent. On IE it can not be called using a constructor.

Here is a polyfill for it:
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill

![image](https://user-images.githubusercontent.com/22659410/73848767-013f3500-4829-11ea-9e3d-afb8484ce99b.png)
```
Unhandled Promise rejection: Object doesn't support this action ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Object doesn't support this action TypeError: Object doesn't support this action
   at Anonymous function (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/builder-webcomponents.js:1:32551)
   at Anonymous function (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/_tslib-dd45d077.js:1:1402)
   at Anonymous function (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/_tslib-dd45d077.js:1:715)
   at n (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/_tslib-dd45d077.js:1:277)
   at ZoneDelegate.prototype.invoke (http://192.168.88.239:5000/polyfills-es5.js:23185:13)
   at Zone.prototype.run (http://192.168.88.239:5000/polyfills-es5.js:22945:17)
   at Anonymous function (http://192.168.88.239:5000/polyfills-es5.js:23705:17)
   at ZoneDelegate.prototype.invokeTask (http://192.168.88.239:5000/polyfills-es5.js:23217:13)
   at
   "Unhandled Promise rejection:"
   "Object doesn't support this action"
   "; Zone:"
   "<root>"
   "; Task:"
   "Promise.then"
   "; Value:"
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support this action",
      message: "Object doesn't support this action",
      name: "TypeError",
      number: -2146827843,
      stack: "TypeError: Object doesn't support this action
   at Anonymous function (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/builder-webcomponents.js:1:32551)
   at Anonymous function (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/_tslib-dd45d077.js:1:1402)
   at Anonymous function (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/_tslib-dd45d077.js:1:715)
   at n (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/_tslib-dd45d077.js:1:277)
   at ZoneDelegate.prototype.invoke (http://192.168.88.239:5000/polyfills-es5.js:23185:13)
   at Zone.prototype.run (http://192.168.88.239:5000/polyfills-es5.js:22945:17)
   at Anonymous function (http://192.168.88.239:5000/polyfills-es5.js:23705:17)
   at ZoneDelegate.prototype.invokeTask (http://192.168.88.239:5000/polyfills-es5.js:23217:13)
   at Zone.prototype.runTask (http://192.168.88.239:5000/polyfills-es5.js:22990:21)
   at drainMicroTaskQueue (http://192.168.88.239:5000/polyfills-es5.js:23396",
      Symbol()_8.zj8vq7cuauw: undefined,
      Symbol()_j.zj8vq7cuaoe: undefined,
      Symbol()_k.zj8vq7cuaoe: undefined,
      Symbol()_p.zj8vq7cuaoe: undefined,
      Symbol(INITIAL_VALUE)_n.zj8vq7cuaoe: undefined,
      Symbol(react.element)_l.zj8vq7cuaoe: undefined,
      Symbol(rxSubscriber)_m.zj8vq7cuaoe: undefined,
      Symbol(rxSubscriber)_o.zj8vq7cuaoe: undefined,
      Symbol(Symbol._hidden)_i.zj8vq7cuaoe: undefined,
      Symbol(target)_q.zj8vq7cuaoe: undefined,
      Symbol(unsubscribe)_r.zj8vq7cuaoe: undefined
   }
   "TypeError: Object doesn't support this action
   at Anonymous function (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/builder-webcomponents.js:1:32551)
   at Anonymous function (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/_tslib-dd45d077.js:1:1402)
   at Anonymous function (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/_tslib-dd45d077.js:1:715)
   at n (https://cdn.builder.io/js/webcomponents@1.0.133/dist/system/angular/_tslib-dd45d077.js:1:277)
   at ZoneDelegate.prototype.invoke (http://192.168.88.239:5000/polyfills-es5.js:23185:13)
   at Zone.prototype.run (http://192.168.88.239:5000/polyfills-es5.js:22945:17)
   at Anonymous function (http://192.168.88.239:5000/polyfills-es5.js:23705:17)
   at ZoneDelegate.prototype.invokeTask (http://192.168.88.239:5000/polyfills-es5.js:23217:13)
   at Zone.prototype.runTask (http://192.168.88.239:5000/polyfills-es5.js:22990:21)
   at drainMicroTaskQueue (http://192.168.88.239:5000/polyfills-es5.js:23396"

```

**Comment by ca136** [comment]
@lyczos should be fixed with `"@builder.io/angular": "1.0.83-alpha.5"`:
https://github.com/BuilderIO/builder/pull/64

I found a few additional issues with IE and the Angular SDK with the recent update to Angular 8. It looks like the angular cli is doing static analysis of the application code to determine which polyfills to bundle. So if the project isn't using CustomEvents, es6 Array methods, etc, then the polyfills won't be included. A good chunk of the Builder SDK is lazy-loaded, so the cli can't analyze it.

In addition, the cli was including the CustomElement polyfill, so when the Builder SDK saw the browser had the customElements property, we loaded our "lite" lib (no polyfills). Anyways, it should be working no, so please let me know if you see any other IE / Edge issues!
